// libs
import { Children } from 'react'
import Head from 'next/head'

// config
import { App } from 'config/app'

function Page({ children }: Children) {
  return (
    <>
      <Head>
        <title>Some Application</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        {/* google fonts - inter */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="use-credentials"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main>
        <App>{children}</App>
      </main>
    </>
  )
}

export { Page }
